version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    environment:
      - MONGODB_URI=mongodb://localhost:27017/
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_PRIMARY_COLOR=#F63366
      - STREAMLIT_THEME_BACKGROUND_COLOR=#FFFFFF
      - STREAMLIT_THEME_SECONDARY_BACKGROUND_COLOR=#F0F2F6
      - STREAMLIT_THEME_TEXT_COLOR=#262730
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=youtube_comments
    command: mongod --bind_ip_all

volumes:
  mongodb_data: